# Generated by Django 5.0.1 on 2025-01-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantreview',
            name='reviewer_name',
            field=models.CharField(default='Гость', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='dish',
            field=models.CharField(default='Все подряд', max_length=200),
        ),
    ]
