version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    environment:
      - DEBUG=1
      - SECRET_KEY=your-secret-key-here
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               python manage.py runserver 0.0.0.0:8000"

volumes:
  media_volume:
  static_volume: 