# Generated by Django 5.0.1 on 2025-01-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='description',
        ),
        migrations.AddField(
            model_name='wine',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='sweetness',
            field=models.CharField(choices=[('dry', 'Сухое'), ('semi_dry', 'Полусухое'), ('semi_sweet', 'Полусладкое'), ('sweet', 'Сладкое')], default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='wine_type',
            field=models.CharField(choices=[('red', 'Красное'), ('white', 'Белое'), ('rose', 'Розовое')], default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winereview',
            name='reviewer_name',
            field=models.CharField(default='Гость', max_length=100),
        ),
    ]
